# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version(">=1.9")

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "minimal/xenial64"

  # Do not update virtual box guest additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "minikube" do |kube|

    kube.vm.hostname = "minikube"

    # Configure virtual hardware
    kube.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = "4"
        vb.name = "minikube"
    end

    # Port for kubernetes dashboard
    kube.vm.network "forwarded_port",
        guest: 30000,
        host:  30000,
        auto_correct: true

    kube.vm.network "forwarded_port",
        guest: 80,
        host:  80,
        auto_correct: true

    kube.vm.network "forwarded_port",
        guest: 443,
        host:  443,
        auto_correct: true

    # Install kubectl CLI
    kube.vm.provision "kubectl", type: "shell", privileged: true, run: "once", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y apt-transport-https bash-completion
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
      apt-get update
      apt-get install -y kubectl
      # Enable bash completion for root
      echo "source /etc/bash_completion" >> ~/.bashrc
      echo "source <(kubectl completion bash)" >> ~/.bashrc
      # Enable bash completion for vagrant
      echo "source /etc/bash_completion" >> /home/vagrant/.bashrc
      echo "source <(kubectl completion bash)" >> /home/vagrant/.bashrc
    SHELL

    # Install docker engine
    kube.vm.provision "docker", type: "shell", privileged: true, run: "once", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get remove docker docker-engine docker.io
      apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update
      apt-get install -y docker-ce=17.03.0~ce-0~ubuntu-xenial
      usermod -aG docker vagrant
      # Test docker installation
      docker run hello-world
      # Clean up hello-world
      docker system prune -a -f
    SHELL

    # Download minikube and add to path
    kube.vm.provision "minikube", type: "shell", privileged: true, run: "once", inline: <<-SHELL
      curl -fsSLo minikube https://storage.googleapis.com/minikube/releases/v0.29.0/minikube-linux-amd64
      chmod +x minikube
      mv minikube /usr/local/bin/
      # Test minikube
      minikube version
      # Enable bash completion
      echo "source <(minikube completion bash)" >> ~/.bashrc
      echo "source <(minikube completion bash)" >> /home/vagrant/.bashrc

      # Disable swap
      sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      swapoff -a
    SHELL

    # Start K8s cluster with minikube
    kube.vm.provision "k8s", type: "shell", privileged: false, run: "once", inline: <<-SHELL
      export MINIKUBE_WANTUPDATENOTIFICATION=false
      export MINIKUBE_WANTREPORTERRORPROMPT=false
      export MINIKUBE_HOME=$HOME
      export CHANGE_MINIKUBE_NONE_USER=true
      export KUBECONFIG=$HOME/.kube/config

      # Create minikube and kube config dir for local user
      mkdir -p $HOME/.kube
      mkdir -p $HOME/.minikube
      touch $HOME/.kube/config

      # set env vars for root
      sudo echo "export CHANGE_MINIKUBE_NONE_USER=true" >> /root/.bashrc
      sudo -E echo "export MINIKUBE_HOME=$MINIKUBE_HOME" >> /root/.bashrc
      sudo -E echo "export KUBECONFIG=$KUBECONFIG" >> /root/.bashrc

      # Run as root
      sudo -E minikube start --vm-driver=none

      # Fix ownership of config files
      sudo chown vagrant. -R /home/vagrant/.minikube
      sudo chown vagrant. -R /home/vagrant/.kube

      # test
      kubectl cluster-info
    SHELL
  end

end
